---
title: "An introduction to the *diwanalr* package"
author: "Peter Watkins"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The **diwanalr** (**di**ffusing-**wa**ve spectroscopy (DWS) **anal**ysis using **R**) package contains a number of functions suitable for analysing DWS data. The package utilises two R packages, *tidyverse* and *ggplot2*, in its implementation.

DWS is derived from dynamic light scattering which is an optical technique that studies the dynamics of scattered light. If carefully calibrated, DWS allows the quantitative measurement of microscopic motion in a soft material from which micro-rheology can be used to determine the rheological properties of a complex medium.

Research capability exists which allows the application of DWS to food systems. In some instances, the analysis of data resulting from such capability can be tedious (e.g. using spreadsheets). This package is intended to allow users of such capability to perform analysis of DWS data in a more straightforward manner.


## Suggested Workflow
At present, there are three stages in the workflow, involving three sets of calculations.

1. *The temporal autocorrelation function*, *g*~1~($t$).
In some cases, the output generated from research equipment consists of a CSV file, with two columns; the first being the correlation time while the second is the measured value of the *intensity autocorrelation function*, noted as *g*~2~($t$). The *g*~2~($t$) values are related to *g*~1~($t$) by the Seigert relationship where *g*~2~($t$) = 1 + $|$*g*~1~($t$)$|$$^2$. The function, *form_g1*, accepts a tibble consisting measured correlation times, $t$, and associated *g*~2~($t$) values, and returns a tibble consisting of three columns; namely, the correlation time ($t$), related *g*~1~($t$) values as well a set of scaled *g*~1~($t$) values, ranging from 0 to approximately 1. The scaled values are deployed in the second step of the workflow. Some functionality is provided to allow the user to set an appropriate normalisation value. The function *plot_g1* is available to visualise the data.

``` 
data(dws)
g1 <- form_g1(dws)
plot_g1(g1)
```


2. *The mean square displacement*.
The next stage involves calculating the mean square displacement (MSD), based on the scaled *g*~1~($t$) values. This involves finding the values which minimise *g*$_{1}$($t$)$\approx\frac{(\frac{L}{l*}+\frac{4}{3})\sqrt{\frac{6t}{\tau}}}{(1+\frac{8t}{3\tau})sinh[\frac{L}{l*}\sqrt{\frac{6t}{\tau}}]+\frac{4}{3}\sqrt{\frac{6t}{\tau}}cosh[\frac{L}{l*}\sqrt{\frac{6t}{\tau}}]}$. This is Equation 16-39b reported in Weitz and Pine, "Diffusing-wave spectroscopy" in Dynamic Light Scattering (ed Wyn Brown), OUP, 1993, pp. 652-720. The function, *form_msd* is used for this purpose, accepting the output from *form_g1* and returning a tibble with the time and related MSD. The function *plot_msd* is available to visualise the output data.

``` 
msd <- form_msd(g1)
plot_msd(msd)
```

3. *The viscoelastic, storage and loss moduli*.
The last stage is to determine the viscoelastic modulus (*G*) from the mean square displacement, which is then used to determine the related storage and loss moduli. The function *form_modulus* is used for this purpose, accepting the output from *form_msd* and returning a tibble with the time and related storage (*G'*) and loss (*G''*) moduli. The function *plot_modulus* is available for visualising the data resulting from the *form_modulus* function.

``` 
mods <- form_modulus(msd)
plot_modulus(mods)
```



